### ISSUE TITLE
If you're looking for a website to test...

### ISSUE THREAD

**Issue by dimitriwalters** [joshfire/jsonform#142]
If you're looking for a website to test JSON objects are in the correct format, [here](http://dimitriwalters.github.io/jsonform-tester/) is a webpage I created for that specific purpose.

I created it because I needed it for my own use-case, but if you find this helpful feel free to link it!

**Comment by codeofsumit** [comment]
doesnt work with my (valid) schema.

Here's a bit more advanced test site to create a form from a schema
http://jeremydorn.com/json-editor/

and of course:

JSON Valdator:
http://jsonformatter.curiousconcept.com/

JSON Schema Validator which also checks if your JSON has the correct Schema structure: http://jsonschemalint.com/

**Comment by dimitriwalters** [comment]
Those tools are great. But the website I created tests a JSON object directly with this library, and it also generated the HTML form too. It was not meant for an all-purpose JSON validator.

Anyways, closing this issue as I just wanted others to know and it's been open long enough.
