### ISSUE TITLE
boolean selectfieldset

### ISSUE THREAD

**Issue by mjau-mjau** [joshfire/jsonform#147]
I am looking into alternative sections, and I see there is an option ```selectfieldset``` that renders keys based on selection. This is nice, but is there no way to render alternative keys based on boolean checkbox and/or radiobuttons?

I simply want to add a checkbox **Use SMTP**, which should render an optional section of input options. Seems a bit silly to use a select field with options "Use SMTP" and "Don't use SMTP".

Any suggestions?

**Comment by ulion** [comment]
Try this:
http://ulion.github.io/jsonform/playground/bootstrap3/?example=fields-checkbox

2015-08-16 0:43 GMT+08:00 Karl Ward <notifications@github.com>:

> I am looking into alternative sections, and I see there is an option
> selectfieldset that renders keys based on selection. This is nice, but is
> there no way to render alternative keys based on boolean checkbox and/or
> radiobuttons?
>
> I am simply want to add a checkbox *Use SMTP*, which should render a new
> section of input options. Seems a bit silly to use a select field with
> options "Use SMTP" and "Don't use SMTP".
>
> Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/147>.
>



-- 
Ulion

**Comment by mjau-mjau** [comment]
ahh ... great! That playground seems to include a few different examples than the one included.

Thanks.

**Comment by mjau-mjau** [comment]
@ulion is that some custom branch or edge version? I can't get that example working here when using identical JSON, and neither can I find any info in the wiki about "customFormItems", "dependencies" or "toggleNext".

**Comment by ulion** [comment]
it's my dev branch, included many my patch and enhancement to jsonform.

2015-08-17 11:34 GMT+08:00 Karl Ward <notifications@github.com>:

> Reopened #147 <https://github.com/joshfire/jsonform/issues/147>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/147#event-383827223>.
>



-- 
Ulion

**Comment by mjau-mjau** [comment]
Nice. Where can I find your dev branch if it is public? This link seems to be dead: http://ulion.github.io/jsonform/

**Comment by ulion** [comment]
https://github.com/ulion/jsonform

2015-08-17 11:38 GMT+08:00 Karl Ward <notifications@github.com>:

> Nice. Where can I find your dev branch if it is public? This link seems to
> be dead: http://ulion.github.io/jsonform/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/147#issuecomment-131671108>.
>



-- 
Ulion

**Comment by mjau-mjau** [comment]
+1 Big Thanks
