### ISSUE TITLE
"required" syntax is not consistent with the json-schema specification.

### ISSUE THREAD

**Issue by scott2b** [joshfire/jsonform#150]
Required properties should be indicated as such with a schema-level property called 'required' which is an array of property names. The current approach of including a required field in each property definition is not consistent with json-schema. See here for an example: http://json-schema.org/examples.html

This break from json-schema compliance means that one cannot share schemata with other compliant validators.

**Comment by ulion** [comment]
it's json schema 3 format.

in my patched branch ulion/jsonform, json schema 4 format "required" is
supported.

2015-10-10 6:11 GMT+08:00 Scott Bradley <notifications@github.com>:

> Required properties should be indicated as such with a schema-level
> property called 'required' which is an array of property names. The current
> approach of including a required field in each property definition is not
> consistent with json-schema. See here for an example:
> http://json-schema.org/examples.html
>
> This break from json-schema compliance means that one cannot share
> schemata with other compliant validators.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshfire/jsonform/issues/150>.
>



-- 
Ulion

**Comment by scott2b** [comment]
Ah, that makes sense. Thanks for quick reply.

**Comment by Jalrom** [comment]
Hi,

I am still facing an issue getting this error when using required in the array form: 
message: "Instance is not a required type"

`
<body>
    <h1>Getting started with JSON Form</h1>
    <form></form>
    <div id="res" class="alert"></div>
    <script src="deps/jquery.min.js"></script>
    <script src="deps/opt/jsv.js"></script>
    <script src="deps/underscore.js"></script>
    <script src="deps/opt/jquery-ui.js"></script>
    <script src="deps/opt/bootstrap-dropdown.js"></script>
    <script src="deps/opt/bootstrap-wysihtml5.js"></script>
    <script src="deps/opt/spectrum.js"></script>
    <script src="deps/opt/ace/ace.js"></script>
    <script src="deps/opt/ace/mode-json.js"></script>
    <script src="deps/opt/ace/mode-html.js"></script>
    <script src="deps/opt/ace/mode-css.js"></script>
    <script src="deps/opt/ace/mode-javascript.js"></script>
    <script src="deps/opt/ace/mode-less.js"></script>
    <script src="deps/opt/ace/mode-markdown.js"></script>
    <script src="deps/opt/jquery.transloadit2.js"></script>
    <script src="lib/jsonform.js"></script>

    <script type="text/javascript">
        var mySchema = {
            "type": "object",
            "properties": {
                "street_address": { "type": "string"},
                "city": { "type": "string" },
                "state": { "type": "string" }
            },
            "required": ["street_address","city"]
        };
        $('form').jsonForm({
            "schema": {
                mySchema
            },
            onSubmitValid: function (values) {
				if (console && console.log) {
					console.log('Values extracted from submitted form', values);
				}
				window.alert('Form submitted. Values object:\n' +
					JSON.stringify(values, null, 2));
			},
			onSubmit: function (errors, values) {
				if (errors) {
					console.log('Validation errors', errors);
					return false;
				}
				return true;
			}
        });

    </script>
</body>
`

In jsonform.js I see this line: 

`
validator = global.JSONFormValidator.createEnvironment("json-schema-draft-03");
`

Am I missing something?

**Comment by tchapi** [comment]
So far jsonform is only compatible with json schema 3.
There is ongoing discussion [here](https://github.com/jsonform/jsonform/issues/200) to implement specifications up to schema v7 — any help is appreciated since I don't have much time to work on that at the moment.
